# keybinds are virtual keys from the win32 api
# you can supply them as an integer or hex value found below
# use `wz-assist getKey` to help with getting a key int
# https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
keybinds:
  # VK_RBUTTON: [RIGHT CLICK]
  ads: 0x02

  # VK_LMENU: [LEFT ALT]
  ping: 0xA4

  # VK_XBUTTON2: [MOUSE BROWSER FORWARD]
  rapidfiretoggle: 0x06

  # toggles recoil handling
  # when NUM LOCK is on recoil will not be handled
  # VK_NUMLOCK: [NUM LOCK]
  recoiltoggle: 0x90

  # toggles between high and low sensitivity
  # when SCROLL LOCK is on high sense is used
  # VK_SCROLL: [SCROLL LOCK]
  recoilsensetoggle: 0x91

# recoilsense controls how fast the mouse moves down the Y axis while firing
# higher = slower
# lower = faster
recoilsense:
  low: 20ms
  high: 14ms

# delays are values that determine how fast a routine runs
delays:
  # this value should not change as it serves as a global routine delay
  # change at your own risk
  standard: 20ms

  # the frequency of how often a ping occurs after firing your weapon
  # it will ping continually while firing
  autopingdelay: 750ms

  # how fast a single fire weapon fires when rapid fire is triggered
  # change at your own risk
  rapidfiredelay: 20ms
